# Generated by Django 3.2.6 on 2021-08-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='student_class',
            field=models.CharField(default='nothing', max_length=10),
            preserve_default=False,
        ),
    ]
