# Generated by Django 3.2.6 on 2021-08-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210813_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDB',
            fields=[
                ('RollNo', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=2)),
                ('Phone', models.IntegerField(max_length=10, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
            ],
        ),
    ]
