# Generated by Django 3.2.6 on 2021-08-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_studentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
    ]
