# Generated by Django 3.2.6 on 2021-08-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_studentdb_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=10)),
                ('Attendance', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('RollNo', models.ForeignKey(db_column='RollNo', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.studentdb')),
            ],
        ),
    ]
